### ISSUE TITLE
Update from from 2.8.14~ynh1 to 2.8.14~ynh3 fails (also restore fails)

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/discourse_ynh#183] opened 2024-05-29 13:23 UTC
### Describe the bug

Full logs here - https://paste.yunohost.org/raw/owipivihug

```
2024-05-29 16:02:47,653: DEBUG - + /opt/rbenv/versions/discourse/bin/gem install bundler
2024-05-29 16:03:31,508: WARNING - ERROR:  Error installing bundler:
2024-05-29 16:03:31,513: WARNING - 	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
2024-05-29 16:03:31,514: WARNING - 	bundler requires Ruby version >= 3.0.0. The current ruby version is 2.7.6.219.
2024-05-29 16:03:31,618: DEBUG - + ynh_exit_properly
2024-05-29 16:03:31,619: DEBUG - + [[ restore =~ ^install$|^upgrade$|^restore$ ]]
2024-05-29 16:03:32,139: DEBUG - + ynh_clean_setup
2024-05-29 16:03:32,139: DEBUG - + ynh_clean_check_starting
2024-05-29 16:03:32,140: DEBUG - + '[' -n '' ']'
2024-05-29 16:03:32,140: DEBUG - + '[' -n '' ']'
2024-05-29 16:03:33,143: ERROR - Could not restore discourse: An error occured inside the app restore script
```

- Hardware: *VPS bought online...*
- YunoHost version: 11.2.12
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no *

**Comment by Salamandar** [comment] 2024-06-13 12:45
Duplicate of #178

**Closed by Salamandar** 2024-06-13 12:45 UTC
